const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const lockScreen=$('#lockScreen'),app=$('#app'),toast=$('#toast');
let currentAccountId='',currentProjectId='',currentCardId='',currentNoteId='',currentDocumentId='',pendingConfirm=null;
const accounts={};
const projects={};
const cards={};
const secureNotes={};
const documents={};

function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function maskLogin(v,key){if(key==='username'||!v.includes('@'))return v;return v.replace(/(^..).+(@.*$)/,'$1••••••$2')}
function providerMeta(key){return key==='gmail'?['Google Hesabı','G','google']:key==='hotmail'?['Microsoft Hesabı','O','hotmail']:key==='username'?['Kullanıcı Adıyla Giriş','KA','username-icon']:['Üyelik Hesabı','H','mail']}
function getAccountServices(id){
  const account=accounts[id];if(!account)return [];
  const manual=(account.services||[]).filter(name=>name!=='Henüz bağlantı yok');
  const linkedProjects=Object.values(projects).filter(project=>project.accountId===id).map(project=>project.title);
  return [...new Set([...linkedProjects,...manual])];
}
function plainNotes(html){const d=document.createElement('div');d.innerHTML=html||'';return (d.innerText||d.textContent||'').trim()}
function notesHtml(text){return `<p>${escapeHtml(text).replace(/\n/g,'<br>')}</p>`}
function cleanCardNumber(value){return value.replace(/\D/g,'').slice(0,19)}
function formatCardNumber(value){return cleanCardNumber(value).replace(/(.{4})/g,'$1 ').trim()}
function maskedCardNumber(value){const number=cleanCardNumber(value),last=number.slice(-4).padStart(4,'•');return `•••• •••• •••• ${last}`}
function openApp(){lockScreen.classList.add('hidden');app.classList.remove('hidden');closeAllModals();showToast('✓ Google hesabı doğrulandı')}
function lockApp(){app.classList.add('hidden');lockScreen.classList.remove('hidden');document.body.classList.remove('privacy')}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2100)}
function openModal(id){closeAllModals();$(id)?.classList.add('show')}
function closeAllModals(){$$('.modal').forEach(m=>m.classList.remove('show'))}
function goToPage(name){$$('.page').forEach(p=>p.classList.remove('active-page'));$(`#${name}Page`)?.classList.add('active-page');$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));window.scrollTo({top:0,behavior:'smooth'})}

function renderAccounts(){
  const entries=Object.entries(accounts);$('#accountGrid').innerHTML=entries.length?entries.map(([id,a])=>{const services=getAccountServices(id);return `<button class="account-card" data-account="${id}" data-provider="${a.providerKey}"><div class="item-top"><div class="record-icon ${a.iconClass}">${escapeHtml(a.icon)}</div><em class="muted-tag">${escapeHtml(a.badge)}</em></div><h3>${escapeHtml(a.name)}</h3><p>${escapeHtml(a.email)}</p><div class="mini-services">${services.length?services.slice(0,3).map(s=>`<span>${escapeHtml(s)}</span>`).join(''):'<span>Henüz bağlantı yok</span>'}</div><div class="connection"><span>◇</span><b>${services.length} bağlı hizmet</b><i>›</i></div></button>`}).join(''):'<div class="empty-record"><span>⌘</span><h3>Henüz hesap yok</h3><p>İlk Gmail, Hotmail veya kullanıcı adı kaydını ekle.</p><button class="open-account-form">＋ Hesap ekle</button></div>';
  const counts={all:Object.keys(accounts).length,gmail:0,hotmail:0,username:0,service:0};Object.values(accounts).forEach(a=>counts[a.providerKey]=(counts[a.providerKey]||0)+1);
  $$('.account-filters button').forEach(b=>{const n=$('b',b);if(n)n.textContent=counts[b.dataset.filter]||0});$('#accountTotalText').textContent=`${counts.all} hesap`;$('#accountSecureText').textContent=`${counts.all} hesap`;$('#accountLinkText').textContent=`${Object.keys(accounts).reduce((sum,id)=>sum+getAccountServices(id).length,0)} bağlantı`;refreshAccountSelect();renderDashboard();
}
function renderProjects(){
  const entries=Object.entries(projects);$('#projectGrid').innerHTML=entries.length?entries.map(([id,p])=>`<button class="project-card" data-project="${id}"><div class="project-cover ${p.cover}"><span>${escapeHtml(p.logo)}</span><em>TEST</em></div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.description)}</p><div class="tag-list">${p.connections.slice(0,3).map(c=>`<span>${escapeHtml(c[1])}</span>`).join('')}</div><footer><span>${p.connections.length} bağlantı</span><i>${escapeHtml(p.account)} ›</i></footer></button>`).join(''):'<div class="empty-record"><span>◇</span><h3>Henüz proje yok</h3><p>Önce bir hesap ekle, ardından projenin bağlantılarını kaydet.</p><button class="open-project-form">＋ Proje ekle</button></div>';renderDashboard();
}
function renderCards(){const entries=Object.entries(cards);$('#cardGrid').innerHTML=entries.length?entries.map(([id,c])=>`<button class="saved-card" data-card="${id}"><div class="saved-card-top"><span>${escapeHtml(c.bank)}</span><em>${escapeHtml(c.type)}</em></div><div class="saved-chip">▦</div><strong>${escapeHtml(maskedCardNumber(c.number))}</strong><footer><span>${escapeHtml(c.name)}</span><b>${escapeHtml(c.expiry)}</b></footer></button>`).join(''):'<div class="empty-record"><span>▰</span><h3>Henüz kart yok</h3><p>Banka veya kredi kartını test amacıyla ekleyebilirsin.</p><button class="open-card-form">＋ Kart ekle</button></div>';renderDashboard()}
function renderSecureNotes(){const entries=Object.entries(secureNotes);$('#noteGrid').innerHTML=entries.length?entries.map(([id,n])=>`<button class="note-card" data-note="${id}"><div><span>▤</span><em>${escapeHtml(n.tag||'NOT')}</em></div><h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(n.content.slice(0,120))}</p><footer>Bu oturumda eklendi <i>›</i></footer></button>`).join(''):'<div class="empty-record"><span>▤</span><h3>Henüz güvenli not yok</h3><p>Test amaçlı ilk notunu ekleyebilirsin.</p><button class="open-note-form">＋ Not ekle</button></div>';renderDashboard()}
function renderDocuments(){const entries=Object.entries(documents);$('#documentGrid').innerHTML=entries.length?entries.map(([id,d])=>`<button class="document-card" data-document="${id}"><div class="document-thumb">${d.isImage&&d.url?`<img src="${d.url}" alt="">`:'<span>▧</span>'}</div><em>${escapeHtml(d.type)}</em><h3>${escapeHtml(d.name)}</h3><p>${escapeHtml(d.fileName||'Dosya seçilmedi')}</p><footer>${escapeHtml(d.note||'Açıklama yok')} <i>›</i></footer></button>`).join(''):'<div class="empty-record"><span>▧</span><h3>Henüz belge yok</h3><p>Test görseli veya PDF kaydı ekleyebilirsin.</p><button class="open-document-form">＋ Belge ekle</button></div>';renderDashboard()}
function renderDashboard(){const ac=Object.keys(accounts).length,pc=Object.keys(projects).length,cc=Object.keys(cards).length,nc=Object.keys(secureNotes).length,dc=Object.keys(documents).length;$('#homeAccountCount').textContent=ac;$('#homeProjectCount').textContent=pc;$('#homeCardCount').textContent=cc;$('#homeNoteCount').textContent=nc;$('#totalRecordCount').textContent=ac+pc+cc+nc+dc;const recent=[];Object.entries(accounts).slice(-1).forEach(([id,a])=>recent.push(`<button class="record-row" data-account="${id}"><div class="record-icon ${a.iconClass}">${escapeHtml(a.icon)}</div><span><b>${escapeHtml(a.name)}</b><small>Hesap · Bu oturumda eklendi</small></span><em class="safe">TEST</em><i>›</i></button>`));Object.entries(projects).slice(-1).forEach(([id,p])=>recent.push(`<button class="record-row" data-project="${id}"><div class="record-icon project">${escapeHtml(p.logo)}</div><span><b>${escapeHtml(p.title)}</b><small>Proje · ${p.connections.length} bağlantı</small></span><em class="linked">PROJE</em><i>›</i></button>`));Object.entries(cards).slice(-1).forEach(([id,c])=>recent.push(`<button class="record-row" data-card="${id}"><div class="record-icon card-mini">▰</div><span><b>${escapeHtml(c.name)}</b><small>${escapeHtml(c.type)} · Sonu ${escapeHtml(cleanCardNumber(c.number).slice(-4))}</small></span><em class="safe">GİZLİ</em><i>›</i></button>`));$('#recentList').innerHTML=recent.length?recent.join(''):'<div class="empty-inline">Henüz kayıt eklenmedi.</div>'}
function refreshAccountSelect(){const s=$('#newProjectAccount'),selected=s.value;s.innerHTML=Object.entries(accounts).map(([id,a])=>`<option value="${id}">${escapeHtml(a.name)}</option>`).join('')||'<option value="">Hesap yok</option>';if(accounts[selected])s.value=selected}

function showAccount(id){const a=accounts[id];if(!a)return;const services=getAccountServices(id);currentAccountId=id;$('#accountDetailTitle').textContent=a.name;$('#accountDetailProvider').textContent=a.provider;$('#accountDetailBadge').textContent=a.badge;const icon=$('#accountDetailIcon');icon.textContent=a.icon;icon.className=`record-icon ${a.iconClass}`;$('#accountEmail').textContent=a.email;$('#accountEmail').dataset.secret=a.fullEmail;$('#accountEmail').dataset.masked=a.email;$('#passwordValue').textContent='••••••••••••••••';$('#passwordValue').dataset.secret=a.password;$('#revealPassword').textContent='◉';$('#accountPurpose').textContent=a.purpose;$('#accountServices').innerHTML='<p>BAĞLI HİZMETLER VE PROJELER</p>'+(services.length?services.map(s=>`<span>◇ ${escapeHtml(s)} <i>›</i></span>`).join(''):'<span>Henüz bağlantı yok</span>');openModal('#accountDetailModal')}
function showProject(id){const p=projects[id];if(!p)return;currentProjectId=id;$('#projectDetailTitle').textContent=p.title;$('#projectDetailDescription').textContent=p.description;$('#projectAccountLink').innerHTML=`⌘ ${escapeHtml(p.account)} <i>›</i>`;$('#projectAccountLink').dataset.account=p.accountId;const logo=$('.project-detail-head .project-logo');logo.textContent=p.logo;logo.className=`project-logo ${p.cover}`;$('#projectConnections').innerHTML=p.connections.map(c=>`<button class="connection-tile" data-url="${escapeHtml(c[3]||'')}" ${c[3]?'title="Bağlantıyı aç"':''}><span>${escapeHtml(c[0])}</span><div><b>${escapeHtml(c[1])}</b><small>${escapeHtml(c[2])}</small></div><i>${c[3]?'↗':'›'}</i></button>`).join('');$('#projectNotesText').innerHTML=p.notes;openModal('#projectDetailModal')}
function showCard(id){const c=cards[id];if(!c)return;currentCardId=id;$('#detailCreditCard').classList.remove('flipped');$('#cardDetailTitle').textContent=c.name;$('#cardDetailBank').textContent=c.bank;$('#cardDetailType').textContent=c.type;$('#cardDetailHolder').textContent=c.holder;$('#cardDetailSignature').textContent=c.holder;$('#cardDetailExpiry').textContent=c.expiry;$('#cardDetailNote').textContent=c.note||'Ek not bulunmuyor.';$('#cardDetailNumber').textContent=maskedCardNumber(c.number);$('#cardDetailCvv').textContent='•••';$('#revealCard').textContent='◉ Bilgileri göster';openModal('#cardDetailModal')}
function showSecureNote(id){const n=secureNotes[id];if(!n)return;currentNoteId=id;$('#noteDetailTag').textContent=n.tag||'GÜVENLİ NOT';$('#noteDetailTitle').textContent=n.title;$('#noteDetailContent').textContent=n.content;openModal('#noteDetailModal')}
function showDocument(id){const d=documents[id];if(!d)return;currentDocumentId=id;$('#documentDetailType').textContent=d.type;$('#documentDetailName').textContent=d.name;$('#documentDetailNote').textContent=d.note||'Açıklama eklenmedi.';const media=d.isImage&&d.url?`<img src="${d.url}" alt="${escapeHtml(d.name)}">`:d.isPdf&&d.url?`<iframe src="${d.url}" title="${escapeHtml(d.name)}"></iframe>`:`<div class="document-file-placeholder"><span>▧</span><b>${escapeHtml(d.fileName||'Dosya seçilmedi')}</b></div>`;$('#documentPreview').innerHTML=`<div class="document-media-stage">${media}</div>${d.url?'<button class="open-document-original">↗ Belgeyi tam boy aç</button>':''}`;openModal('#documentDetailModal')}

function prepareAccountForm(id=''){const form=$('#accountForm');form.reset();form.dataset.mode=id?'edit':'add';form.dataset.editingId=id;$('.modal-head .eyebrow',form).textContent=id?'HESABI DÜZENLE':'YENİ HESAP';$('.modal-head h2',form).textContent=id?'Hesap bilgilerini güncelle':'E-posta veya kullanıcı hesabı ekle';$('button[type="submit"]',form).textContent=id?'Değişiklikleri kaydet':'Hesabı deneme listesine ekle';if(id){const a=accounts[id];$('#newAccountName').value=a.name;$('#newAccountProvider').value=a.providerKey;$('#newAccountEmail').value=a.fullEmail;$('#newAccountPassword').value=a.password;$('#newAccountUrl').value=a.url||'';$('#newAccountPurpose').value=a.purpose;$('#newAccountServices').value=a.services.join(', ')}openModal('#accountFormModal')}
function prepareProjectForm(id=''){const form=$('#projectForm');form.reset();refreshAccountSelect();form.dataset.mode=id?'edit':'add';form.dataset.editingId=id;form._preservedConnections=[];$('.modal-head .eyebrow',form).textContent=id?'PROJEYİ DÜZENLE':'YENİ PROJE';$('.modal-head h2',form).textContent=id?'Program bilgilerini ve bağlantıları güncelle':'Program ve çalışma notu ekle';$('button[type="submit"]',form).textContent=id?'Değişiklikleri kaydet':'Projeyi deneme listesine ekle';const summary=$('#projectConnectionSummary');summary.innerHTML='';if(id){const p=projects[id],find=n=>p.connections.find(c=>c[1].toLowerCase().includes(n));form._preservedConnections=p.connections.map(c=>[...c]);$('#newProjectName').value=p.title;$('#newProjectDescription').value=p.description;$('#newProjectAccount').value=p.accountId;$('#newProjectHosting').value=(find('vercel')||find('netlify')||find('cloudflare')||find('yerel')||['','Diğer'])[1];$('#newProjectGithub').value=(find('github')||[])[3]||(find('github')||[])[2]||'';$('#newProjectFirebase').value=(find('firebase')||[])[3]||(find('firebase')||[])[2]||'';$('#newProjectLive').value=(find('canlı')||[])[3]||(find('canlı')||[])[2]||'';$('#newProjectNotes').value=plainNotes(p.notes);summary.innerHTML='<b>MEVCUT BAĞLANTILAR</b><p>Kaydettiğinde aşağıdaki özel bağlantılar korunur.</p><div>'+p.connections.map(c=>`<span><i>${escapeHtml(c[0])}</i><strong>${escapeHtml(c[1])}</strong><small>${escapeHtml(c[2])}</small></span>`).join('')+'</div>'}openModal('#projectFormModal')}
function prepareCardForm(id=''){const form=$('#cardForm');form.reset();form.dataset.editingId=id;$('.modal-head .eyebrow',form).textContent=id?'KARTI DÜZENLE':'YENİ KART';$('.modal-head h2',form).textContent=id?'Kart bilgilerini güncelle':'Banka veya kredi kartı ekle';$('button[type="submit"]',form).textContent=id?'Değişiklikleri kaydet':'Kartı deneme listesine ekle';if(id){const c=cards[id];$('#newCardName').value=c.name;$('#newCardBank').value=c.bank;$('#newCardType').value=c.type;$('#newCardHolder').value=c.holder;$('#newCardNumber').value=formatCardNumber(c.number);$('#newCardExpiry').value=c.expiry;$('#newCardCvv').value=c.cvv;$('#newCardNote').value=c.note||''}openModal('#cardFormModal')}
function prepareNoteForm(id=''){const form=$('#noteForm');form.reset();form.dataset.editingId=id;$('.modal-head h2',form).textContent=id?'Güvenli notu düzenle':'Yeni not ekle';$('button[type="submit"]',form).textContent=id?'Değişiklikleri kaydet':'Notu deneme listesine ekle';if(id){const n=secureNotes[id];$('#newNoteTitle').value=n.title;$('#newNoteTag').value=n.tag;$('#newNoteContent').value=n.content}openModal('#noteFormModal')}
function prepareDocumentForm(id=''){const form=$('#documentForm');form.reset();form.dataset.editingId=id;$('.modal-head h2',form).textContent=id?'Belge kaydını düzenle':'Yeni belge ekle';$('button[type="submit"]',form).textContent=id?'Değişiklikleri kaydet':'Belgeyi deneme listesine ekle';$('#newDocumentFile').required=!id;if(id){const d=documents[id];$('#newDocumentName').value=d.name;$('#newDocumentType').value=d.type;$('#newDocumentNote').value=d.note;$('#documentFileHint').textContent=`Mevcut dosya: ${d.fileName}. Değiştirmek istemiyorsan yeni dosya seçme.`}else $('#documentFileHint').textContent='⚠ Test için örnek bir görsel veya PDF seç. Gerçek kişisel belge kullanma.';openModal('#documentFormModal')}

function confirmAction(title,message,action){$('#confirmTitle').textContent=title;$('#confirmMessage').textContent=message;pendingConfirm=action;openModal('#confirmModal')}
async function copyValue(value,label){try{await navigator.clipboard.writeText(value)}catch{const t=document.createElement('textarea');t.value=value;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}showToast(`✓ ${label} kopyalandı`)}

$('#biometricBtn').onclick=()=>document.dispatchEvent(new CustomEvent('firebase-sign-in-request'));document.addEventListener('firebase-auth-ready',e=>{const user=e.detail,$status=$('#firebaseAuthStatus');if(user){$status.textContent=`Hazır: ${user.email||'Google hesabı'}`;const name=user.displayName||'Mustafa Yargın',initials=name.split(' ').map(x=>x[0]).join('').slice(0,2).toLocaleUpperCase('tr');$('.profile-mini>div').textContent=initials;$('.profile-mini b').textContent=name;$('.profile-mini small').textContent=user.email||'Firebase kullanıcısı'}else $status.textContent='Google hesabınla giriş yap'});document.addEventListener('firebase-authenticated',e=>{const btn=$('#biometricBtn');btn.innerHTML='<span class="fingerprint">G</span><span><b>Doğrulandı</b><small>Kasa açılıyor...</small></span><strong>✓</strong>';setTimeout(openApp,500)});document.addEventListener('firebase-auth-error',e=>showToast(`! ${e.detail||'Google girişi başarısız'}`));$('#passwordBtn').onclick=()=>showToast('! Önce Google hesabınla giriş yap');$('#unlockPassword').onclick=()=>showToast('! Önce Google hesabınla giriş yap');$('#demoPassword').addEventListener('keydown',e=>{if(e.key==='Enter')showToast('! Önce Google hesabınla giriş yap')});$('#desktopLock').onclick=lockApp;$('#mobileLock').onclick=lockApp;
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>goToPage(b.dataset.page)));$$('.open-add').forEach(b=>b.addEventListener('click',()=>openModal('#addModal')));
document.addEventListener('click',e=>{if(e.target.closest('.open-document-original')){const d=documents[currentDocumentId];if(d?.url)window.open(d.url,'_blank','noopener');return}const account=e.target.closest('[data-account]');if(account&&!account.closest('#projectDetailModal')){showAccount(account.dataset.account);return}const project=e.target.closest('[data-project]');if(project){showProject(project.dataset.project);return}const card=e.target.closest('[data-card]');if(card){showCard(card.dataset.card);return}const note=e.target.closest('[data-note]');if(note){showSecureNote(note.dataset.note);return}const documentCard=e.target.closest('[data-document]');if(documentCard){showDocument(documentCard.dataset.document);return}const link=e.target.closest('.connection-tile');if(link?.dataset.url){window.open(link.dataset.url,'_blank','noopener');return}if(e.target.closest('.open-account-form')){prepareAccountForm();return}if(e.target.closest('.open-project-form')){if(!Object.keys(accounts).length){closeAllModals();goToPage('accounts');showToast('! Önce projeyi bağlayacağın hesabı ekle');return}prepareProjectForm();return}if(e.target.closest('.open-card-form')){prepareCardForm();return}if(e.target.closest('.open-note-form')){prepareNoteForm();return}if(e.target.closest('.open-document-form')){prepareDocumentForm();return}const coming=e.target.closest('[data-coming]');if(coming?.dataset.coming==='Kart formu'){prepareCardForm();return}if(coming?.dataset.coming==='Not formu'){prepareNoteForm();return}if(coming?.dataset.coming==='Belge formu'){prepareDocumentForm();return}if(coming){closeAllModals();showToast(`＋ ${coming.dataset.coming} sonraki aşamada hazırlanacak`)}});

$('#projectAccountLink').onclick=e=>{if(e.currentTarget.dataset.account)showAccount(e.currentTarget.dataset.account)};$('#revealPassword').onclick=()=>{const n=$('#passwordValue'),hidden=n.textContent.includes('•');n.textContent=hidden?n.dataset.secret:'••••••••••••••••';$('#revealPassword').textContent=hidden?'⊘':'◉';if(hidden)setTimeout(()=>{n.textContent='••••••••••••••••';$('#revealPassword').textContent='◉'},7000)};$('#accountEmail').onclick=()=>{const n=$('#accountEmail');if(n.dataset.secret)n.textContent=n.textContent.includes('•')?n.dataset.secret:n.dataset.masked};$('#copyAccountLogin').onclick=()=>copyValue(accounts[currentAccountId]?.fullEmail||'','Kullanıcı bilgisi');$('#copyAccountPassword').onclick=()=>copyValue(accounts[currentAccountId]?.password||'','Parola');
$('#editAccountBtn').onclick=()=>prepareAccountForm(currentAccountId);$('#deleteAccountBtn').onclick=()=>{const id=currentAccountId,a=accounts[id];if(!a)return;const linked=Object.values(projects).filter(p=>p.accountId===id).length;confirmAction('Hesabı silmek istiyor musun?',`${a.name} kaldırılacak.${linked?` Bu hesaba bağlı ${linked} projenin hesap bağlantısı boşaltılacak.`:''}`,()=>{delete accounts[id];Object.values(projects).forEach(p=>{if(p.accountId===id){p.accountId='';p.account='Hesap silindi'}});renderAccounts();renderProjects();closeAllModals();goToPage('accounts');showToast('✓ Hesap silindi')})};
$('#editProjectBtn').onclick=()=>prepareProjectForm(currentProjectId);$('#deleteProjectBtn').onclick=()=>{const id=currentProjectId,p=projects[id];if(!p)return;confirmAction('Projeyi silmek istiyor musun?',`${p.title} ve bu oturumdaki notları kaldırılacak.`,()=>{delete projects[id];renderProjects();renderAccounts();closeAllModals();goToPage('projects');showToast('✓ Proje silindi')})};$('#addConnectionBtn').onclick=()=>{$('#connectionForm').reset();openModal('#connectionFormModal')};$('#editNotesBtn').onclick=()=>{$('#editableProjectNotes').value=plainNotes(projects[currentProjectId]?.notes||'');openModal('#notesFormModal')};
$('#editCardBtn').onclick=()=>prepareCardForm(currentCardId);$('#deleteCardBtn').onclick=()=>{const id=currentCardId,c=cards[id];if(!c)return;confirmAction('Kartı silmek istiyor musun?',`${c.name} bu oturumdaki listeden kaldırılacak.`,()=>{delete cards[id];renderCards();closeAllModals();goToPage('cards');showToast('✓ Kart silindi')})};
$('#editNoteBtn').onclick=()=>prepareNoteForm(currentNoteId);$('#deleteNoteBtn').onclick=()=>{const id=currentNoteId,n=secureNotes[id];if(!n)return;confirmAction('Notu silmek istiyor musun?',`${n.title} bu oturumdaki listeden kaldırılacak.`,()=>{delete secureNotes[id];renderSecureNotes();closeAllModals();goToPage('notes');showToast('✓ Güvenli not silindi')})};
$('#editDocumentBtn').onclick=()=>prepareDocumentForm(currentDocumentId);$('#deleteDocumentBtn').onclick=()=>{const id=currentDocumentId,d=documents[id];if(!d)return;confirmAction('Belgeyi silmek istiyor musun?',`${d.name} ve seçilen test dosyası kaldırılacak.`,()=>{if(d.url)URL.revokeObjectURL(d.url);delete documents[id];renderDocuments();closeAllModals();goToPage('documents');showToast('✓ Belge silindi')})};
$('#cancelConfirm').onclick=()=>{pendingConfirm=null;closeAllModals()};$('#approveConfirm').onclick=()=>{const action=pendingConfirm;pendingConfirm=null;action?.()};

$('#accountForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,editing=form.dataset.editingId,providerKey=$('#newAccountProvider').value,name=$('#newAccountName').value.trim(),login=$('#newAccountEmail').value.trim(),duplicate=Object.entries(accounts).some(([id,a])=>id!==editing&&a.fullEmail.toLocaleLowerCase('tr')===login.toLocaleLowerCase('tr'));if(duplicate){showToast('! Bu giriş bilgisi zaten kayıtlı');return}const id=editing||`demo-account-${Date.now()}`,[provider,icon,iconClass]=providerMeta(providerKey),services=$('#newAccountServices').value.split(',').map(s=>s.trim()).filter(Boolean),url=$('#newAccountUrl').value.trim();if(url&&!services.includes(url))services.unshift(url);accounts[id]={name,provider,providerKey,email:maskLogin(login,providerKey),fullEmail:login,password:$('#newAccountPassword').value,url,badge:editing?accounts[id].badge:'DENEME',purpose:$('#newAccountPurpose').value.trim()||'Kullanım amacı belirtilmedi.',icon,iconClass,services:services.length?services:['Henüz bağlantı yok']};renderAccounts();form.reset();closeAllModals();goToPage('accounts');showToast(editing?'✓ Hesap güncellendi':'✓ Hesap deneme listesine eklendi')};
$('#projectForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,editing=form.dataset.editingId,title=$('#newProjectName').value.trim(),duplicate=Object.entries(projects).some(([id,p])=>id!==editing&&p.title.toLocaleLowerCase('tr')===title.toLocaleLowerCase('tr'));if(duplicate){showToast('! Bu proje adı zaten kayıtlı');return}const id=editing||`demo-project-${Date.now()}`,accountId=$('#newProjectAccount').value,account=accounts[accountId]?.name||'Hesap seçilmedi',hosting=$('#newProjectHosting').value,github=$('#newProjectGithub').value.trim(),firebase=$('#newProjectFirebase').value.trim(),live=$('#newProjectLive').value.trim(),connections=[];if(github)connections.push(['GH','GitHub',github,github.startsWith('http')?github:'']);if(firebase)connections.push(['FB','Firebase',firebase,firebase.startsWith('http')?firebase:'']);if(hosting)connections.push(['↗',hosting,live||'Yayın adresi henüz eklenmedi',live.startsWith('http')?live:'']);if(live&&!connections.some(c=>c[3]===live))connections.push(['↗','Canlı Adres',live,live.startsWith('http')?live:'']);const managed=new Set(['github','firebase','vercel','netlify','cloudflare','yerel exe','diğer','canlı adres','bağlantı yok']);(form._preservedConnections||[]).filter(c=>!managed.has(c[1].toLocaleLowerCase('tr'))).forEach(c=>{if(!connections.some(x=>x[1]===c[1]&&x[2]===c[2]&&x[3]===c[3]))connections.push(c)});projects[id]={title,description:$('#newProjectDescription').value.trim()||'Yeni proje',account,accountId,logo:title.slice(0,2).toLocaleUpperCase('tr'),cover:editing?projects[id].cover:'network',connections:connections.length?connections:[['◇','Bağlantı yok','Daha sonra eklenebilir','']],notes:notesHtml($('#newProjectNotes').value.trim()||'Çalışma notları henüz eklenmedi.')};renderProjects();renderAccounts();form.reset();closeAllModals();goToPage('projects');showToast(editing?'✓ Proje ve bağlantıları güncellendi':'✓ Proje deneme listesine eklendi')};
$('#connectionForm').onsubmit=e=>{e.preventDefault();const p=projects[currentProjectId];if(!p)return;const name=$('#connectionName').value.trim(),info=$('#connectionInfo').value.trim(),url=$('#connectionUrl').value.trim();p.connections.push([name.slice(0,2).toLocaleUpperCase('tr'),name,info||url||'Açıklama eklenmedi',url.startsWith('http')?url:'']);renderProjects();showProject(currentProjectId);showToast('✓ Bağlantı projeye eklendi')};$('#notesForm').onsubmit=e=>{e.preventDefault();const p=projects[currentProjectId];if(!p)return;p.notes=notesHtml($('#editableProjectNotes').value.trim());renderProjects();showProject(currentProjectId);showToast('✓ Proje notları güncellendi')};

$('#newCardNumber').addEventListener('input',e=>{e.target.value=formatCardNumber(e.target.value)});$('#newCardExpiry').addEventListener('input',e=>{const n=e.target.value.replace(/\D/g,'').slice(0,4);e.target.value=n.length>2?`${n.slice(0,2)}/${n.slice(2)}`:n});
$('#cardForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,editing=form.dataset.editingId,number=cleanCardNumber($('#newCardNumber').value),expiry=$('#newCardExpiry').value.trim(),cvv=$('#newCardCvv').value.replace(/\D/g,'');if(number.length<13){showToast('! Kart numarası eksik');return}if(!/^\d{2}\/\d{2}$/.test(expiry)){showToast('! Son kullanma tarihi AA/YY olmalı');return}if(cvv.length<3){showToast('! CVV en az 3 rakam olmalı');return}const duplicate=Object.entries(cards).some(([id,c])=>id!==editing&&cleanCardNumber(c.number)===number);if(duplicate){showToast('! Bu kart zaten kayıtlı');return}const id=editing||`demo-card-${Date.now()}`;cards[id]={name:$('#newCardName').value.trim(),bank:$('#newCardBank').value.trim(),type:$('#newCardType').value,holder:$('#newCardHolder').value.trim().toLocaleUpperCase('tr'),number,expiry,cvv,note:$('#newCardNote').value.trim()};renderCards();form.reset();closeAllModals();goToPage('cards');showToast(editing?'✓ Kart güncellendi':'✓ Kart deneme listesine eklendi')};
$('#noteForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,editing=form.dataset.editingId,title=$('#newNoteTitle').value.trim(),duplicate=Object.entries(secureNotes).some(([id,n])=>id!==editing&&n.title.toLocaleLowerCase('tr')===title.toLocaleLowerCase('tr'));if(duplicate){showToast('! Bu not başlığı zaten kayıtlı');return}const id=editing||`demo-note-${Date.now()}`;secureNotes[id]={title,tag:$('#newNoteTag').value.trim(),content:$('#newNoteContent').value.trim()};renderSecureNotes();form.reset();closeAllModals();goToPage('notes');showToast(editing?'✓ Güvenli not güncellendi':'✓ Güvenli not eklendi')};
$('#documentForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,editing=form.dataset.editingId,file=$('#newDocumentFile').files[0],name=$('#newDocumentName').value.trim(),duplicate=Object.entries(documents).some(([id,d])=>id!==editing&&d.name.toLocaleLowerCase('tr')===name.toLocaleLowerCase('tr'));if(duplicate){showToast('! Bu belge adı zaten kayıtlı');return}if(!editing&&!file){showToast('! Bir test görseli veya PDF seç');return}const id=editing||`demo-document-${Date.now()}`,old=documents[id]||{},nextFile=file||old.file,url=file?URL.createObjectURL(file):old.url;if(file&&old.url)URL.revokeObjectURL(old.url);documents[id]={name,type:$('#newDocumentType').value,note:$('#newDocumentNote').value.trim(),file:nextFile,fileName:nextFile?.name||'',mimeType:nextFile?.type||'',isImage:(nextFile?.type||'').startsWith('image/'),isPdf:(nextFile?.type||'')==='application/pdf',url};renderDocuments();form.reset();closeAllModals();goToPage('documents');showToast(editing?'✓ Belge kaydı güncellendi':'✓ Belge deneme listesine eklendi')};

$('#flipCard').onclick=()=>$('#detailCreditCard').classList.toggle('flipped');$('#revealCard').onclick=()=>{const c=cards[currentCardId];if(!c)return;const hidden=$('#cardDetailNumber').textContent.includes('•');$('#cardDetailNumber').textContent=hidden?formatCardNumber(c.number):maskedCardNumber(c.number);$('#cardDetailCvv').textContent=hidden?c.cvv:'•••';$('#revealCard').textContent=hidden?'◉ Bilgileri gizle':'◉ Bilgileri göster';if(hidden)setTimeout(()=>{if(cards[currentCardId]){$('#cardDetailNumber').textContent=maskedCardNumber(cards[currentCardId].number);$('#cardDetailCvv').textContent='•••';$('#revealCard').textContent='◉ Bilgileri göster'}},7000)};$('#privacyBtn').onclick=()=>{document.body.classList.toggle('privacy');showToast(document.body.classList.contains('privacy')?'◉ Gizlilik modu açık':'◉ Gizlilik modu kapalı')};
$$('.account-filters button').forEach(btn=>btn.onclick=()=>{$$('.account-filters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.account-card').forEach(c=>c.style.display=btn.dataset.filter==='all'||c.dataset.provider===btn.dataset.filter?'block':'none')});$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase('tr');if(!q){$$('.account-card,.project-card').forEach(c=>c.style.display='block');return}goToPage('accounts');$$('.account-card').forEach(c=>c.style.display=c.textContent.toLocaleLowerCase('tr').includes(q)?'block':'none')});
['.close-modal','.close-account-detail','.close-project-detail','.close-account-form','.close-project-form','.close-card-form','.close-card-detail','.close-note-form','.close-note-detail','.close-document-form','.close-document-detail','.close-connection-form','.close-notes-form','.close-password'].forEach(s=>$(s)?.addEventListener('click',closeAllModals));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeAllModals()}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAllModals();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});
renderAccounts();renderProjects();renderCards();renderSecureNotes();renderDocuments();
