import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js';
import {getAuth,GoogleAuthProvider,onAuthStateChanged,setPersistence,browserLocalPersistence,signInWithPopup} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBN6JnGRn1p37lCsdtavqaryqr3JfF4yYE',authDomain:'kisisel-kasa.firebaseapp.com',projectId:'kisisel-kasa',storageBucket:'kisisel-kasa.firebasestorage.app',messagingSenderId:'432687211408',appId:'1:432687211408:web:d6a252b049c8ea135c4915'};
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp),provider=new GoogleAuthProvider();
provider.setCustomParameters({prompt:'select_account'});
let vaultKey=null,currentRecord=null;
window.firebaseAuthState={auth,user:null};

const enc=new TextEncoder(),dec=new TextDecoder();
const bytesToB64=bytes=>btoa(String.fromCharCode(...bytes));
const b64ToBytes=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
const b64url=bytes=>bytesToB64(bytes).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const emit=(name,detail)=>document.dispatchEvent(new CustomEvent(name,{detail}));
const emptyVault=()=>({accounts:{},projects:{},cards:{},secureNotes:{},documents:{}});
const vaultRef=()=>doc(db,'users',auth.currentUser.uid,'vault','main');
function friendlyError(error){const code=error?.code||'';if(code.includes('popup-closed-by-user'))return 'Google giriş penceresi kapatıldı';if(code.includes('popup-blocked'))return 'Tarayıcı giriş penceresini engelledi';if(code.includes('unauthorized-domain'))return 'Bu adres Firebase yetkili alanlarına eklenmemiş';if(code.includes('network-request-failed'))return 'İnternet bağlantısı kurulamadı';if(code.includes('permission-denied'))return 'Firestore erişimi güvenlik kuralı tarafından engellendi';return error?.message||'İşlem tamamlanamadı'}
async function passwordKey(password,salt){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function recoveryKey(code){const normalized=code.trim().replace(/\s+/g,'').toUpperCase(),hash=await crypto.subtle.digest('SHA-256',enc.encode(normalized));return crypto.subtle.importKey('raw',hash,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function cryptBytes(key,bytes){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes);return {iv:bytesToB64(iv),cipher:bytesToB64(new Uint8Array(cipher))}}
async function decryptBytes(key,box){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(box.iv)},key,b64ToBytes(box.cipher)))}
async function encryptData(data){return cryptBytes(vaultKey,enc.encode(JSON.stringify(data)))}
async function decryptData(record,key=vaultKey){return JSON.parse(dec.decode(await decryptBytes(key,record.data)))}
async function exportVaultKey(){return new Uint8Array(await crypto.subtle.exportKey('raw',vaultKey))}
async function wrapVaultKey(kek){return cryptBytes(kek,await exportVaultKey())}
async function unwrapVaultKey(kek,box){const raw=await decryptBytes(kek,box);return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},true,['encrypt','decrypt'])}
function newRecoveryCode(){const raw=crypto.getRandomValues(new Uint8Array(24)),plain=b64url(raw).toUpperCase();return plain.match(/.{1,4}/g).join('-')}
async function buildV2(data,password){vaultKey=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']);const salt=crypto.getRandomValues(new Uint8Array(16)),pKey=await passwordKey(password,salt),code=newRecoveryCode(),rKey=await recoveryKey(code);return {record:{version:2,data:await encryptData(data),password:{salt:bytesToB64(salt),...(await wrapVaultKey(pKey))},recovery:await wrapVaultKey(rKey)},code}}
async function saveRecord(record){currentRecord=record;await setDoc(vaultRef(),{...record,updatedAt:serverTimestamp()})}

await setPersistence(auth,browserLocalPersistence);
onAuthStateChanged(auth,async user=>{window.firebaseAuthState.user=user;emit('firebase-auth-ready',user?{uid:user.uid,email:user.email,displayName:user.displayName,photoURL:user.photoURL}:null);if(user){try{const snap=await getDoc(vaultRef());currentRecord=snap.exists()?snap.data():null;emit('vault-password-required',{exists:!!currentRecord})}catch(error){emit('firebase-auth-error',friendlyError(error))}}});
document.addEventListener('firebase-sign-in-request',async()=>{try{const result=auth.currentUser?{user:auth.currentUser}:await signInWithPopup(auth,provider);emit('firebase-authenticated',{uid:result.user.uid,email:result.user.email,displayName:result.user.displayName,photoURL:result.user.photoURL})}catch(error){emit('firebase-auth-error',friendlyError(error))}});

document.addEventListener('vault-unlock-request',async event=>{try{const password=event.detail?.password||'';if(password.length<10)throw new Error('Ana parola en az 10 karakter olmalı');const snap=await getDoc(vaultRef());currentRecord=snap.exists()?snap.data():null;if(!currentRecord){const built=await buildV2(emptyVault(),password);await saveRecord(built.record);emit('vault-loaded',emptyVault());emit('recovery-code-created',{code:built.code,reason:'new'});return}if(currentRecord.version===2){const pKey=await passwordKey(password,b64ToBytes(currentRecord.password.salt));vaultKey=await unwrapVaultKey(pKey,currentRecord.password);emit('vault-loaded',await decryptData(currentRecord));return}const oldSalt=b64ToBytes(currentRecord.salt),oldKey=await passwordKey(password,oldSalt),plain=JSON.parse(dec.decode(await decryptBytes(oldKey,currentRecord)));const built=await buildV2(plain,password);await saveRecord(built.record);emit('vault-loaded',plain);emit('recovery-code-created',{code:built.code,reason:'migration'})}catch(error){vaultKey=null;emit('vault-error',error?.name==='OperationError'?'Ana parola yanlış':friendlyError(error))}});
document.addEventListener('vault-save-request',async event=>{if(!vaultKey||!auth.currentUser)return;try{const data=await encryptData(event.detail);if(data.cipher.length>880000)throw new Error('Kasa boyutu Firestore sınırına yaklaştı. Büyük belgeleri küçült.');await saveRecord({...currentRecord,version:2,data});emit('vault-saved')}catch(error){emit('vault-error',friendlyError(error))}});
document.addEventListener('vault-recover-request',async event=>{try{const {code,newPassword}=event.detail||{};if(newPassword.length<10)throw new Error('Yeni ana parola en az 10 karakter olmalı');const snap=await getDoc(vaultRef());currentRecord=snap.data();if(currentRecord?.version!==2)throw new Error('Kasa önce yeni güvenlik yapısına geçirilmelidir');vaultKey=await unwrapVaultKey(await recoveryKey(code),currentRecord.recovery);const salt=crypto.getRandomValues(new Uint8Array(16)),pKey=await passwordKey(newPassword,salt);await saveRecord({...currentRecord,password:{salt:bytesToB64(salt),...(await wrapVaultKey(pKey))}});emit('vault-recovered');emit('vault-loaded',await decryptData(currentRecord))}catch(error){vaultKey=null;emit('vault-error',error?.name==='OperationError'?'Kurtarma anahtarı geçersiz':friendlyError(error))}});
document.addEventListener('recovery-rotate-request',async()=>{try{if(!vaultKey)throw new Error('Önce kasayı aç');const code=newRecoveryCode(),rKey=await recoveryKey(code);await saveRecord({...currentRecord,recovery:await wrapVaultKey(rKey)});emit('recovery-code-created',{code,reason:'rotate'})}catch(error){emit('vault-error',friendlyError(error))}});
document.addEventListener('vault-backup-request',async()=>{try{const snap=await getDoc(vaultRef()),record=snap.data();const backup={format:'KISISEL-KASA-YEDEK',backupVersion:1,ownerUid:auth.currentUser.uid,exportedAt:new Date().toISOString(),vault:record};delete backup.vault.updatedAt;const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kisisel-kasa-yedek-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);emit('vault-backup-ready')}catch(error){emit('vault-error',friendlyError(error))}});
document.addEventListener('vault-import-request',async event=>{try{const backup=JSON.parse(event.detail.text);if(backup.format!=='KISISEL-KASA-YEDEK'||backup.backupVersion!==1||!backup.vault)throw new Error('Geçerli bir Kişisel Kasa yedeği değil');if(backup.ownerUid!==auth.currentUser.uid)throw new Error('Bu yedek farklı bir Google hesabına ait');vaultKey=null;await saveRecord(backup.vault);emit('vault-imported');emit('vault-password-required',{exists:true})}catch(error){emit('vault-error',friendlyError(error))}});
